//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NProxy.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NProxy.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot adapt instance to interface type.
        /// </summary>
        internal static string Error_CannotAdaptInstance {
            get {
                return ResourceManager.GetString("Error_CannotAdaptInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor on type &apos;{0}&apos; not found.
        /// </summary>
        internal static string Error_ConstructorOnTypeNotFound {
            get {
                return ResourceManager.GetString("Error_ConstructorOnTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic assembly key pair is missing.
        /// </summary>
        internal static string Error_DynamicAssemblyKeyPairIsMissing {
            get {
                return ResourceManager.GetString("Error_DynamicAssemblyKeyPairIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface type &apos;{0}&apos; must not be a generic type definition.
        /// </summary>
        internal static string Error_InterfaceTypeMustNotBeAGenericTypeDefinition {
            get {
                return ResourceManager.GetString("Error_InterfaceTypeMustNotBeAGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface type must not be null.
        /// </summary>
        internal static string Error_InterfaceTypeMustNotBeNull {
            get {
                return ResourceManager.GetString("Error_InterfaceTypeMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface type {0} was already added.
        /// </summary>
        internal static string Error_InterfaceTypeWasAlreadyAdded {
            get {
                return ResourceManager.GetString("Error_InterfaceTypeWasAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid instance type.
        /// </summary>
        internal static string Error_InvalidInstanceType {
            get {
                return ResourceManager.GetString("Error_InvalidInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member has no declaring type.
        /// </summary>
        internal static string Error_MemberHasNoDeclaringType {
            get {
                return ResourceManager.GetString("Error_MemberHasNoDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not declared or inherited by target object.
        /// </summary>
        internal static string Error_MethodNotDeclaredOrInherited {
            get {
                return ResourceManager.GetString("Error_MethodNotDeclaredOrInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not implemented or inherited by target object.
        /// </summary>
        internal static string Error_MethodNotImplementedOrInherited {
            get {
                return ResourceManager.GetString("Error_MethodNotImplementedOrInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is not inherited by target object.
        /// </summary>
        internal static string Error_MethodNotInherited {
            get {
                return ResourceManager.GetString("Error_MethodNotInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is not overridable.
        /// </summary>
        internal static string Error_MethodNotOverridable {
            get {
                return ResourceManager.GetString("Error_MethodNotOverridable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; on type &apos;{1}&apos; not found.
        /// </summary>
        internal static string Error_MethodOnTypeNotFound {
            get {
                return ResourceManager.GetString("Error_MethodOnTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method requires a target object.
        /// </summary>
        internal static string Error_MethodRequiresATargetObject {
            get {
                return ResourceManager.GetString("Error_MethodRequiresATargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more interceptors in the interceptor chain.
        /// </summary>
        internal static string Error_NoMoreInterceptorsInTheInterceptorChain {
            get {
                return ResourceManager.GetString("Error_NoMoreInterceptorsInTheInterceptorChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameter types and parameter names must be equal.
        /// </summary>
        internal static string Error_NumberOfParameterTypesAndParameterNamesMustBeEqual {
            get {
                return ResourceManager.GetString("Error_NumberOfParameterTypesAndParameterNamesMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent type must not be a generic type definition.
        /// </summary>
        internal static string Error_ParentTypeMustNotBeAGenericTypeDefinition {
            get {
                return ResourceManager.GetString("Error_ParentTypeMustNotBeAGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent type must not be sealed.
        /// </summary>
        internal static string Error_ParentTypeMustNotBeSealed {
            get {
                return ResourceManager.GetString("Error_ParentTypeMustNotBeSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an interface type.
        /// </summary>
        internal static string Error_TypeNotAnInterfaceType {
            get {
                return ResourceManager.GetString("Error_TypeNotAnInterfaceType", resourceCulture);
            }
        }
    }
}
